### PR TITLE
added LAST PLAYED GAME category

### PR DESCRIPTION
**Pull request by fwannmacher**
A new category was created: LAST PLAYED GAME. With this category the app will open with the last launched game highlighted within it respective category.

### CODE REVIEW

**Comment by BlackSheepBoy69** [comment]
I tested this feature and I love it!! Retroflow (the sister project to HexLauncher Custom) is running some bugtests to make sure their latest release is stable then I'll put HexLauncher Custom v1.1 with "LAST PLAYED" but I have to wait because it will use some of Retroflow's framework and I would want it to be as good as it can be, thank you for the "pull" though!!!!

**Comment by fwannmacher** [comment]
I'm glad you liked it :-) Feel free to do any changes you want as I just wanted to give the idea and help a bit ;-)

**Comment by BlackSheepBoy69** [comment]
Sorry it's taken so long to reply back to you, I had some really high priorities for good features and they're constantly fighting with each other (rolling cache, RetroFlow, among many others). I'll be sure to merge the pull request right before I'm done so you can get the achievement on your profile, it's just I'll have to edit it again to work with RetroFlow.

The way you set it up right now could technically work but if you had 2 games of the same name for different systems it would have an issue of maybe selecting the right one and it might be overkill, I just wanted to do it right.

The next update will probably be the last one and I'll be sure to have this feature and it should finally be soon but I just wanted to apologize for taking so long.

**Comment by fwannmacher** [comment]
No problem at all. Take your time ;)

**Pull request merged**
